<div class="container">
    <div class="row mb-10">
        <h5 class="text-center mb-3">
            <b>DATA PRIVACY CONSENT FOR {{ strtoupper(config('company.company_name')) }} PERSONNEL</b>
        </h5>

        <h6 class="text-success mt-4 mb-3">
            <b>Introduction</b>
        </h6>

        <p class="mb-3">
            In compliance with RA 10173, or the Data Privacy Act of 2012 (DPA), its Implementing Rules and
            Regulations (IRR), and other relevant policies, including issuances of the National Privacy
            Commission, the {{ config('company.company_name') }} crafted its Privacy Notice, which can be accessed via its
            official website.
            <br><br>
            {{ config('company.company_name') }} respects and upholds data privacy rights and aims to comply with the
            requirements of the DPA.
            This policy ensures that all personal data collected from potential and on-deck teaching and
            non-teaching personnel are processed, pursuant to the general principles of transparency,
            legitimate purpose, and proportionality, as stipulated in the Act.
        </p>

        <h6 class="text-success mt-4 mb-3">
            <b>Consent on Information Collected, Acquired, or Generated by {{ config('company.company_name') }}</b>
        </h6>

        <div class="card card-body border mb-3">
            <p>
                I agree to the collection of my personal and privileged information in written form,
                photographic and video images, and digital material.
                Examples but is not limited to the following:
            </p>

            <ul class="ms-3 mb-0">
                <li class="mb-2">
                    <b>Information provided or generated prior to my engagement.</b>
                    <i>
                        <ol class="ps-4">
                            <li>Personal Data Sheet (PDS);</li>
                            <li>resume and/or curriculum vitae;</li>
                            <li>Transcript of Records;</li>
                            <li>details about my professional license, if any; and</li>
                            <li>additional information generated from the interview.</li>
                        </ol>
                        If I am already engaged by the University, it may use the information already in its
                        possession to process my application for a new or different position.
                    </i>
                </li>
                <li class="mb-2">
                    <b>Information collected or generated upon issuance of an employment offer or the
                        commencement of my engagement.</b>
                    <i>
                        <ol class="ps-4">
                            <li>Certificate of Employment;</li>
                            <li>Medical/Fit-to-Work Clearance;</li>
                            <li>NBI Clearance;</li>
                            <li>Philippine Statistics Authority (PSA) Birth Certificate
                                (applicant/dependents);</li>
                            <li>PSA Marriage Contract;</li>
                            <li>SSS ID;</li>
                            <li>Pag-IBIG Member's Data Form and/or ID;</li>
                            <li>Pag-IBIG Member's Change in Information Form (MCIF);</li>
                            <li>PhilHealth MDR or ID;</li>
                            <li>PhilHealth Member Registration Form; and</li>
                            <li>tax-related documents, such as your TIN ID or BIR Form 1902 (with stamp) and
                                2316.</li>
                        </ol>
                    </i>
                </li>
                {{-- <li class="mb-2">
                    <b>Information collected or generated during the course of my employment or engagement
                        with the University.</b>
                    <i>
                        <ol class="ps-4">
                            <li>annual physical examination results;</li>
                            <li>other data that may be used in the processing of loan applications and
                                insurance claims, in performance evaluation, and in administrative and
                                disciplinary cases; and</li>
                            <li>pictures or videos of activities I participated in, via official
                                documentation of such activities, or through recordings from official video
                                platforms.</li>
                        </ol>
                    </i>
                </li> --}}
                <li>
                    <b>Unsolicited Information.</b>
                    <p class="ms-2">
                        <i>
                            There may be instances when my personal information is sent to or received by
                            the University even without my prior request.
                            In such cases, I understand that {{ config('company.company_name') }} will determine if it can
                            legitimately keep such information.
                            If it is not related to any of its legitimate interests, it will immediately
                            dispose the information in a way that will safeguard my privacy.
                            Otherwise, it will be treated in the same manner as information I have provided
                            with the University.
                        </i>
                    </p>
                </li>
            </ul>

            <p class="ms-4 mb-0">
                If I will supply the University with personal data of other individuals (e.g., person to
                contact in the event of an emergency, professional referees), the University will request
                from me a certification that I have obtained the consent of such individuals before
                providing the University with their personal data.
            </p>
        </div>

        <h6 class="text-success mt-4 mb-3">
            <b>Consent on How The Company Uses My Information</b>
        </h6>

        <div class="card card-body border mb-3">
            <p>
                I agree that to the extent permitted or required by law, my personal data will be used
                in pursuit of legitimate interests as an educational institution, employer, and/or
                contracting party, including a variety of administrative, research, historical, and
                statistical purposes.
                Details are as follows:
            </p>

            <ul class="ms-3 mb-0">
                <li>identifying applicants and processing their respective applications;</li>
                <li>assessing the suitability of candidates for a particular role or position;</li>
                <li>verifying the provided or submitted information;</li>
                <li>checking background information;</li>
                <li>evaluating academic qualifications;</li>
                <li>supporting personnel when implementing health-related adjustments that will allow
                    him/her to carry out a particular role or task;</li>
                <li>administering remuneration, payroll, pension, and other standard employment functions;
                </li>
                <li>administering human resource-related processes, including those relating to performance
                    management, and disciplinary issues;</li>
                <li>delivering or providing facilities, services, security, and staff benefits to employees;
                </li>
                <li>facilitating claims and remittances for mandatory benefits;</li>
                <li>communicating effectively with personnel, including the distribution of relevant
                    newsletters and circulars;</li>
                <li>supporting personnel training, health, safety, welfare and religious requirements;</li>
                <li>compiling statistics and conducting surveys and research for internal and statutory
                    reporting purposes;</li>
                <li>enabling the Human Resource Management Department to contact others in the event of an
                    emergency; and</li>
                <li>other similar or related tasks.</li>
            </ul>
        </div>

        <div class="card card-body border mb-3">
            <p>
                I agree that the processing of my personal data for these purposes are necessary for the
                performance of my obligations to the University, for its compliance with a legal
                obligation, to protect my vitally important interests, including my life and health, for
                the performance of tasks it carry out in the public interest (e.g., public order, public
                safety, etc.), or for the pursuit of the legitimate interests of the University or a
                third party.
            </p>
        </div>

        <div class="card card-body border mb-3">
            <p>
                I understand that the DPA imposes stricter rules for the processing of sensitive
                personal information and privileged information, and that {{ config('company.company_name') }} is fully
                committed to abiding by those rules.
                <br>
                If {{ config('company.company_name') }} will require my consent for any specific use of my personal
                data, it will be collected at the appropriate time.
            </p>
        </div>

        <div class="card card-body border mb-3">
            <p>
                I understand that {{ config('company.company_name') }} will not subject my personal data to any
                automated decision-making process without my prior consent.
            </p>
        </div>

        {{-- <h6 class="text-success mt-4 mb-3">
            <b>Consent on How {{ config('company.company_name') }} Shares, Discloses, or Transfers My Information</b>
        </h6>

        <div class="card card-body border mb-3">
            <p>
                I understand that utmost care and due diligence are practiced by the University in
                handling personal data.
                The University shall never share or disclose data to third-parties without prior consent
                from the data subjects.
                Whenever disclosure of data is necessary and permitted, the University will
                conscientiously reviews the privacy and security policies of the authorized third-party
                service providers or external partners.
                The University may also be required to disclose data in compliance with legal or
                regulatory obligations.
            </p>
        </div>

        <div class="card card-body border mb-3">
            <p>
                To the extent permitted or required by law, I understand that {{ config('company.company_name') }} may
                also share, disclose, or transfer my personal data to other persons or organizations in
                order to uphold my interests and/or pursue its legitimate interests as an educational
                institution.
                For example, {{ config('company.company_name') }} may share, disclose, or transfer your personal data
                for purposes such as:
            </p>

            <ul class="ms-3 mb-0">
                <li>submission of information to government agencies such as the City Government of Cabuyao,
                    Commission on Higher Education and Department of Education, for accreditation and
                    reportorial requirements; the Government Service Insurance System, Philippine Health
                    Insurance Corporation, Pag-IBIG, and Bureau of Internal Revenue, for the provision of
                    employment benefits mandated by law;</li>
                <li>sharing information with entities or organizations (e.g., ALCUCOA and ISO 9001:2015
                    Certifying Body) for accreditation and certification purposes;</li>
                <li>disclosure of my information related to Termination of Employment, Flexible
                    Fixed/Variable Work Arrangements, Employees Compensation Report to the Civil Service
                    Commission, as part of the University's reportorial obligations; and</li>
                <li>other purposes, when necessary and under circumstances permitted or required by law.
                </li>
            </ul>
        </div> --}}

        <h6 class="text-success mt-4 mb-3">
            <b>Consent on How {{ config('company.company_name') }} Stores and Retains My Information</b>
        </h6>

        <div class="card card-body border mb-3">
            <p>
                I understand that my personal data is stored and transmitted securely in a variety of
                paper and electronic formats, including databases that are shared between the University
                and its different units or offices.
                Access to my personal data is limited to University personnel who have a legitimate
                interest in them for the purpose of carrying out their contractual duties.
                I am confident that use of my personal data will not be excessive, and shall be limited
                to that which is necessary to achieve the purpose of their collection, and/or only when
                permitted by law.
            </p>

            <p class="ms-4 my-1">
                In retaining my personal information, {{ config('company.company_name') }} generally subscribe to the
                following schedule:
            </p>

            <ul class="ms-3 mb-0">
                <li>Employees. One year (1) from the day of your separation from the Company or the
                    termination of your employment, after which your employment records (e.g., 201 file) in
                    HRMD are classified as Dead Files, subject to applicable Company policies.</li>
                <li>Job applicants. Seven (7) months to one (1) year for pooling purposes, after which they
                    are disposed of in a secure and safe manner, if not used within said period.</li>
            </ul>
        </div>

        <div class="card card-body border mb-3">
            <p>
                I understand that {{ config('company.company_name') }} will retain relevant personal data indefinitely
                for historical and statistical purposes unless otherwise provided by law or by
                appropriate University policies.
            </p>
        </div>

        <h6 class="text-success mt-4 mb-3">
            <b>Consent on My Rights with Respect to My Personal Data</b>
        </h6>

        <div class="card card-body border mb-3">
            <p>
                I understand that {{ config('company.company_name') }} recognizes my rights with respect to personal
                data, as provided by the DPA.
                Should I wish to exercise any of these rights, or should I have any concern or question
                regarding them, this Notice, or any matter involving the University and data privacy, I
                may contact the Data Privacy Officer of {{ config('company.company_name') }} at the following:
            </p>

            <ul class="ms-0 ps-0 mt-5" type="none">
                <li><b>{{ config('company.company_address') }}</b></li>
                <li><b>{{ config('company.company_email') }}</b></li>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="form-check">
            <input class="form-check-input " type="checkbox" value="1" name="data_privacy_act"/>
            <label class="form-check-label" for="flexCheckDefault">
                I have read and agree to the Privacy Consent
            </label>
        </div>

    </div>
</div>
